#pragma config(Sensor, dgtl1,  ultrasonics,    sensorSONAR_inch)
#pragma config(Sensor, dgtl12, touchs,         sensorTouch)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		// when touch sensor is NOT pressed, drives back
		while(SensorValue(touchs) == 0)
		{
			motor[left] = -50;
			motor[right] = -50;
		}
		//  when ultrasonic sensor is NOT detected, drives forward
		while(SensorValue(ultrasonics) > 5 || SensorValue(ultrasonics) == -1)
		{
			motor[left] = 50;
			motor[right] = 50;
		}
	}

}
