#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor[left] = 50;
motor[right] = 50;
wait1Msec(2000);

motor[left] = 50;
motor[right] = -50;
wait1Msec(900);

motor[left] = 50;
motor[right] = 50;
wait1Msec(2000);

motor[left] = 50;
motor[right] = -50;
wait1Msec(900);

motor[left] = 50;
motor[right] = 50;
wait1Msec(2000);

motor[left] = 50;
motor[right] = -50;
wait1Msec(900);

motor[left] = 50;
motor[right] = 50;
wait1Msec(2000);



}
