#pragma config(Sensor, dgtl1,  ultrasonicS,    sensorSONAR_inch)
#pragma config(Sensor, dgtl12, touchS,         sensorTouch)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveStraight(float speed)
{motor[left] = speed;
	motor[right] = speed;
	}



void charge(float time, float speed)
{moveStraight(-50);
	wait1Msec(time);
	motor[left] = speed;
	motor[right] = -speed;
	wait1Msec(1700);
	moveStraight(100);
	wait1Msec(2000);
}


void pickup()
{




motor[left] = 40;
	motor[right] = -40;





	while (SensorValue(ultrasonicS) >= 6 || SensorValue(ultrasonicS) == -1)
{wait1Msec(1);}

wait1Msec(2);

if (SensorValue(ultrasonicS) < 6 && SensorValue(ultrasonicS) >= 0)
{motor[left] = 0;
	motor[right] = 0;
	wait1Msec(1000);
	wait1Msec(1000);
	charge(3300, 50);
	}


}


task main()
{
	while (1 ==1)
	{
pickup();
}

}
