#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



int speed = 0;

task main()
{
  while(1 == 1)
  {
    //motor[leftMotor]  = vexRT[Ch3 / 2];   // Left Joystick Y value
    //motor[rightMotor] = vexRT[Ch2 / 2];   // Right Joystick Y value


  motor[left] = speed;
	motor[right] = speed;



	//decelerate
	while	(vexRT[Btn5D] == 1)
	{
	speed = speed - 1;
	motor[left] = speed;
	motor[right] = speed;
	wait1Msec(100);
	}


	//accelerate
	while	(vexRT[Btn6D] == 1)
	{
	speed = speed + 1;
	motor[left] = speed ;
	motor[right] = speed;
	wait1Msec(100);
	}



	//reverse
if (vexRT[Btn8D] == 1)
{	speed = speed * -1;
	motor[left] = speed ;
	motor[right] = speed;
	wait1Msec(2000);}


	//right turn
	while	(vexRT[Btn8R] == 1)
	{
	motor[right] = speed - (speed * 0.55) ;
	motor[left] = speed + (speed * 0.55);
	}


	//left turn
	while	(vexRT[Btn8L] == 1)
	{
	motor[left] = speed - (speed * 0.55) ;
	motor[right] = speed + (speed * 0.55);
	}


	//off
if (vexRT[Btn7D] == 1 && speed != 0)
{	speed = 0;
	wait1Msec(1000);
	}



	//on
if (vexRT[Btn7D] == 1 && speed == 0)
{	speed = 40;
	wait1Msec(1000);
}


	//back,spin,forward
if (vexRT[Btn8U] == 1)
{	speed = speed + 10;
  motor[left] = -speed;
	motor[right] = -speed;
	wait1Msec(2500);
	motor[left] = -speed;
	motor[right] = speed;
	wait1Msec(2500);
	motor[left] = speed;
	motor[right] = speed;
	wait1Msec(2500);
	}




	}
}
