#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void spin(int power, int dur)
{
	motor[left] = -power;
	motor[right] = power;
	wait1Msec(dur);

}



task main()
{
spin(80, 3000);
spin(0, 2000);
spin(-30, 1000);



}
