#pragma config(Sensor, dgtl1,  ultrasoundS,    sensorSONAR_inch)
#pragma config(Sensor, dgtl12, touchS,         sensorTouch)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           hand,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveForward(float speed)
{motor[left] = speed;
	motor[right] = speed ;}



void turn(float power)
{motor[left] = -power;
	motor[right] = power;}



void moveArm(float power)
{motor[arm] = power;}




void moveHand(float power)
{motor[hand] = power;}



void victoryDance()
{

	moveForward(-50);
	wait1Msec(750);
	playSound(soundBeepBeep);
	turn(100);
	wait1Msec(1000);

}



task main()
{
moveArm(20);
	//1.

	moveForward(-50);

	while (SensorValue(touchS) == 0)
	{wait1Msec(1);}

	if (SensorValue(touchS) == 1)
	{playSound(soundBeepBeep);
		moveForward(50); }



	//2.



	while(SensorValue(ultrasoundS) >= 8 || SensorValue(ultrasoundS) == -1)
	{wait1Msec(1);}

	moveForward(0);
	wait1Msec(100);

	if(SensorValue(ultrasoundS) < 8 && SensorValue(ultrasoundS) >= 0)
	{moveForward(-50);
		wait1Msec(400);
		turn(50);
		wait1Msec(950);
		moveForward(50);
	}


	//3.
	while(SensorValue(ultrasoundS) >= 6 || SensorValue(ultrasoundS) == -1)
	{wait1Msec(1);}

	moveForward(0);
	wait1Msec(10);


	while(SensorValue(ultrasoundS) < 6 && SensorValue(ultrasoundS) >= 0)
	{wait1Msec(1);
		playSound(soundBeepBeep);}


	wait1Msec(10);

	if(SensorValue(ultrasoundS) >= 6 || SensorValue(ultrasoundS) == -1)
	{moveForward(30);
		wait1Msec(300);
		moveForward(0);
		moveArm(-50);
		wait1Msec(300);
		moveHand(-100);
		wait1Msec(1000);
		moveHand(100);
		wait1Msec(1000);
		moveArm(50);
	wait1Msec(500);
	moveArm(35);
	}



	//4

	turn(50);
	wait1Msec(1900);
	moveForward(50);

	while(SensorValue(ultrasoundS) >= 6 || SensorValue(ultrasoundS) == -1)
	{wait1Msec(1);}

	moveForward(0);
	wait1Msec(10);

	while(SensorValue(ultrasoundS) < 6 && SensorValue(ultrasoundS) >= 0)
	{wait1Msec(1);
		playSound(soundBeepBeep);}

	wait1Msec(10);


	if(SensorValue(ultrasoundS) >= 6 || SensorValue(ultrasoundS) == -1)
	{moveArm(-50);
		wait1Msec(300);
		moveHand(-100);
		wait1Msec(1000);
		moveArm(50);
		wait1Msec(300);
		moveArm(20);
	}

	victoryDance();
	wait1Msec(40);
}
